name: run

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 30 04,23 * * ?
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: run
        env:
         PARAMETER: ${{ secrets.PARAMETER }}
        run: |
         bash CnUnicom.sh $PARAMETER
